/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.carlosduran.liferay.lim.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import net.carlosduran.liferay.lim.service.persistence.Installations_ModulesPK;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Installations_Modules service. Represents a row in the &quot;LIM_Installations_Modules&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>net.carlosduran.liferay.lim.model.impl.Installations_ModulesModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>net.carlosduran.liferay.lim.model.impl.Installations_ModulesImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Installations_Modules
 * @generated
 */
@ProviderType
public interface Installations_ModulesModel
	extends BaseModel<Installations_Modules> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a installations_ modules model instance should use the {@link Installations_Modules} interface instead.
	 */

	/**
	 * Returns the primary key of this installations_ modules.
	 *
	 * @return the primary key of this installations_ modules
	 */
	public Installations_ModulesPK getPrimaryKey();

	/**
	 * Sets the primary key of this installations_ modules.
	 *
	 * @param primaryKey the primary key of this installations_ modules
	 */
	public void setPrimaryKey(Installations_ModulesPK primaryKey);

	/**
	 * Returns the uuid of this installations_ modules.
	 *
	 * @return the uuid of this installations_ modules
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this installations_ modules.
	 *
	 * @param uuid the uuid of this installations_ modules
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the installation ID of this installations_ modules.
	 *
	 * @return the installation ID of this installations_ modules
	 */
	public long getInstallationId();

	/**
	 * Sets the installation ID of this installations_ modules.
	 *
	 * @param installationId the installation ID of this installations_ modules
	 */
	public void setInstallationId(long installationId);

	/**
	 * Returns the module ID of this installations_ modules.
	 *
	 * @return the module ID of this installations_ modules
	 */
	public long getModuleId();

	/**
	 * Sets the module ID of this installations_ modules.
	 *
	 * @param moduleId the module ID of this installations_ modules
	 */
	public void setModuleId(long moduleId);

}