/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.carlosduran.liferay.lim.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Scheme service. Represents a row in the &quot;LIM_Scheme&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>net.carlosduran.liferay.lim.model.impl.SchemeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>net.carlosduran.liferay.lim.model.impl.SchemeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Scheme
 * @generated
 */
@ProviderType
public interface SchemeModel extends BaseModel<Scheme> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a scheme model instance should use the {@link Scheme} interface instead.
	 */

	/**
	 * Returns the primary key of this scheme.
	 *
	 * @return the primary key of this scheme
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this scheme.
	 *
	 * @param primaryKey the primary key of this scheme
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this scheme.
	 *
	 * @return the uuid of this scheme
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this scheme.
	 *
	 * @param uuid the uuid of this scheme
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the scheme ID of this scheme.
	 *
	 * @return the scheme ID of this scheme
	 */
	public long getSchemeId();

	/**
	 * Sets the scheme ID of this scheme.
	 *
	 * @param schemeId the scheme ID of this scheme
	 */
	public void setSchemeId(long schemeId);

	/**
	 * Returns the name of this scheme.
	 *
	 * @return the name of this scheme
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this scheme.
	 *
	 * @param name the name of this scheme
	 */
	public void setName(String name);

	/**
	 * Returns the server hostname of this scheme.
	 *
	 * @return the server hostname of this scheme
	 */
	@AutoEscape
	public String getServerHostname();

	/**
	 * Sets the server hostname of this scheme.
	 *
	 * @param serverHostname the server hostname of this scheme
	 */
	public void setServerHostname(String serverHostname);

	/**
	 * Returns the server ip of this scheme.
	 *
	 * @return the server ip of this scheme
	 */
	@AutoEscape
	public String getServerIP();

	/**
	 * Sets the server ip of this scheme.
	 *
	 * @param serverIP the server ip of this scheme
	 */
	public void setServerIP(String serverIP);

	/**
	 * Returns the db user of this scheme.
	 *
	 * @return the db user of this scheme
	 */
	@AutoEscape
	public String getDbUser();

	/**
	 * Sets the db user of this scheme.
	 *
	 * @param dbUser the db user of this scheme
	 */
	public void setDbUser(String dbUser);

	/**
	 * Returns the db pass of this scheme.
	 *
	 * @return the db pass of this scheme
	 */
	@AutoEscape
	public String getDbPass();

	/**
	 * Sets the db pass of this scheme.
	 *
	 * @param dbPass the db pass of this scheme
	 */
	public void setDbPass(String dbPass);

	/**
	 * Returns the db name of this scheme.
	 *
	 * @return the db name of this scheme
	 */
	@AutoEscape
	public String getDbName();

	/**
	 * Sets the db name of this scheme.
	 *
	 * @param dbName the db name of this scheme
	 */
	public void setDbName(String dbName);

}