/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.carlosduran.liferay.lim.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Site service. Represents a row in the &quot;LIM_Site&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>net.carlosduran.liferay.lim.model.impl.SiteModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>net.carlosduran.liferay.lim.model.impl.SiteImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Site
 * @generated
 */
@ProviderType
public interface SiteModel extends BaseModel<Site> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a site model instance should use the {@link Site} interface instead.
	 */

	/**
	 * Returns the primary key of this site.
	 *
	 * @return the primary key of this site
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this site.
	 *
	 * @param primaryKey the primary key of this site
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the site ID of this site.
	 *
	 * @return the site ID of this site
	 */
	public long getSiteId();

	/**
	 * Sets the site ID of this site.
	 *
	 * @param siteId the site ID of this site
	 */
	public void setSiteId(long siteId);

	/**
	 * Returns the name of this site.
	 *
	 * @return the name of this site
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this site.
	 *
	 * @param name the name of this site
	 */
	public void setName(String name);

	/**
	 * Returns the private site of this site.
	 *
	 * @return the private site of this site
	 */
	public boolean getPrivateSite();

	/**
	 * Returns <code>true</code> if this site is private site.
	 *
	 * @return <code>true</code> if this site is private site; <code>false</code> otherwise
	 */
	public boolean isPrivateSite();

	/**
	 * Sets whether this site is private site.
	 *
	 * @param privateSite the private site of this site
	 */
	public void setPrivateSite(boolean privateSite);

	/**
	 * Returns the friendly url of this site.
	 *
	 * @return the friendly url of this site
	 */
	@AutoEscape
	public String getFriendlyUrl();

	/**
	 * Sets the friendly url of this site.
	 *
	 * @param friendlyUrl the friendly url of this site
	 */
	public void setFriendlyUrl(String friendlyUrl);

	/**
	 * Returns the virtualhost of this site.
	 *
	 * @return the virtualhost of this site
	 */
	@AutoEscape
	public String getVirtualhost();

	/**
	 * Sets the virtualhost of this site.
	 *
	 * @param virtualhost the virtualhost of this site
	 */
	public void setVirtualhost(String virtualhost);

	/**
	 * Returns the description of this site.
	 *
	 * @return the description of this site
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this site.
	 *
	 * @param description the description of this site
	 */
	public void setDescription(String description);

	/**
	 * Returns the installation ID of this site.
	 *
	 * @return the installation ID of this site
	 */
	public long getInstallationId();

	/**
	 * Sets the installation ID of this site.
	 *
	 * @param installationId the installation ID of this site
	 */
	public void setInstallationId(long installationId);

}