/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.carlosduran.liferay.lim.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import net.carlosduran.liferay.lim.model.Installations_Modules;
import net.carlosduran.liferay.lim.service.Installations_ModulesLocalService;
import net.carlosduran.liferay.lim.service.persistence.InstallationPersistence;
import net.carlosduran.liferay.lim.service.persistence.Installations_ModulesPK;
import net.carlosduran.liferay.lim.service.persistence.Installations_ModulesPersistence;
import net.carlosduran.liferay.lim.service.persistence.ModulePersistence;
import net.carlosduran.liferay.lim.service.persistence.SchemePersistence;
import net.carlosduran.liferay.lim.service.persistence.SitePersistence;
import net.carlosduran.liferay.lim.service.persistence.VMPersistence;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the installations_ modules local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link net.carlosduran.liferay.lim.service.impl.Installations_ModulesLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see net.carlosduran.liferay.lim.service.impl.Installations_ModulesLocalServiceImpl
 * @generated
 */
public abstract class Installations_ModulesLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   Installations_ModulesLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>Installations_ModulesLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>net.carlosduran.liferay.lim.service.Installations_ModulesLocalServiceUtil</code>.
	 */

	/**
	 * Adds the installations_ modules to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect Installations_ModulesLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param installations_Modules the installations_ modules
	 * @return the installations_ modules that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Installations_Modules addInstallations_Modules(
		Installations_Modules installations_Modules) {

		installations_Modules.setNew(true);

		return installations_ModulesPersistence.update(installations_Modules);
	}

	/**
	 * Creates a new installations_ modules with the primary key. Does not add the installations_ modules to the database.
	 *
	 * @param installations_ModulesPK the primary key for the new installations_ modules
	 * @return the new installations_ modules
	 */
	@Override
	@Transactional(enabled = false)
	public Installations_Modules createInstallations_Modules(
		Installations_ModulesPK installations_ModulesPK) {

		return installations_ModulesPersistence.create(installations_ModulesPK);
	}

	/**
	 * Deletes the installations_ modules with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect Installations_ModulesLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param installations_ModulesPK the primary key of the installations_ modules
	 * @return the installations_ modules that was removed
	 * @throws PortalException if a installations_ modules with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Installations_Modules deleteInstallations_Modules(
			Installations_ModulesPK installations_ModulesPK)
		throws PortalException {

		return installations_ModulesPersistence.remove(installations_ModulesPK);
	}

	/**
	 * Deletes the installations_ modules from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect Installations_ModulesLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param installations_Modules the installations_ modules
	 * @return the installations_ modules that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Installations_Modules deleteInstallations_Modules(
		Installations_Modules installations_Modules) {

		return installations_ModulesPersistence.remove(installations_Modules);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			Installations_Modules.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return installations_ModulesPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>net.carlosduran.liferay.lim.model.impl.Installations_ModulesModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return installations_ModulesPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>net.carlosduran.liferay.lim.model.impl.Installations_ModulesModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return installations_ModulesPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return installations_ModulesPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return installations_ModulesPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public Installations_Modules fetchInstallations_Modules(
		Installations_ModulesPK installations_ModulesPK) {

		return installations_ModulesPersistence.fetchByPrimaryKey(
			installations_ModulesPK);
	}

	/**
	 * Returns the installations_ modules with the primary key.
	 *
	 * @param installations_ModulesPK the primary key of the installations_ modules
	 * @return the installations_ modules
	 * @throws PortalException if a installations_ modules with the primary key could not be found
	 */
	@Override
	public Installations_Modules getInstallations_Modules(
			Installations_ModulesPK installations_ModulesPK)
		throws PortalException {

		return installations_ModulesPersistence.findByPrimaryKey(
			installations_ModulesPK);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			installations_ModulesLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Installations_Modules.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"primaryKey.installationId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			installations_ModulesLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			Installations_Modules.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"primaryKey.installationId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			installations_ModulesLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Installations_Modules.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"primaryKey.installationId");
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return installations_ModulesPersistence.create(
			(Installations_ModulesPK)primaryKeyObj);
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return installations_ModulesLocalService.deleteInstallations_Modules(
			(Installations_Modules)persistedModel);
	}

	public BasePersistence<Installations_Modules> getBasePersistence() {
		return installations_ModulesPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return installations_ModulesPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the installations_ moduleses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>net.carlosduran.liferay.lim.model.impl.Installations_ModulesModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of installations_ moduleses
	 * @param end the upper bound of the range of installations_ moduleses (not inclusive)
	 * @return the range of installations_ moduleses
	 */
	@Override
	public List<Installations_Modules> getInstallations_Moduleses(
		int start, int end) {

		return installations_ModulesPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of installations_ moduleses.
	 *
	 * @return the number of installations_ moduleses
	 */
	@Override
	public int getInstallations_ModulesesCount() {
		return installations_ModulesPersistence.countAll();
	}

	/**
	 * Updates the installations_ modules in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect Installations_ModulesLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param installations_Modules the installations_ modules
	 * @return the installations_ modules that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Installations_Modules updateInstallations_Modules(
		Installations_Modules installations_Modules) {

		return installations_ModulesPersistence.update(installations_Modules);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			Installations_ModulesLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		installations_ModulesLocalService =
			(Installations_ModulesLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return Installations_ModulesLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Installations_Modules.class;
	}

	protected String getModelClassName() {
		return Installations_Modules.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				installations_ModulesPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected InstallationPersistence installationPersistence;

	protected Installations_ModulesLocalService
		installations_ModulesLocalService;

	@Reference
	protected Installations_ModulesPersistence installations_ModulesPersistence;

	@Reference
	protected ModulePersistence modulePersistence;

	@Reference
	protected SchemePersistence schemePersistence;

	@Reference
	protected SitePersistence sitePersistence;

	@Reference
	protected VMPersistence vmPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}