/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.carlosduran.liferay.lim.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import javax.sql.DataSource;

import net.carlosduran.liferay.lim.model.Installation;
import net.carlosduran.liferay.lim.service.InstallationService;
import net.carlosduran.liferay.lim.service.persistence.InstallationPersistence;
import net.carlosduran.liferay.lim.service.persistence.Installations_ModulesPersistence;
import net.carlosduran.liferay.lim.service.persistence.ModulePersistence;
import net.carlosduran.liferay.lim.service.persistence.SchemePersistence;
import net.carlosduran.liferay.lim.service.persistence.SitePersistence;
import net.carlosduran.liferay.lim.service.persistence.VMPersistence;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the installation remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link net.carlosduran.liferay.lim.service.impl.InstallationServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see net.carlosduran.liferay.lim.service.impl.InstallationServiceImpl
 * @generated
 */
public abstract class InstallationServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, IdentifiableOSGiService, InstallationService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>InstallationService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>net.carlosduran.liferay.lim.service.InstallationServiceUtil</code>.
	 */
	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			InstallationService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		installationService = (InstallationService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return InstallationService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Installation.class;
	}

	protected String getModelClassName() {
		return Installation.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = installationPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected net.carlosduran.liferay.lim.service.InstallationLocalService
		installationLocalService;

	protected InstallationService installationService;

	@Reference
	protected InstallationPersistence installationPersistence;

	@Reference
	protected Installations_ModulesPersistence installations_ModulesPersistence;

	@Reference
	protected ModulePersistence modulePersistence;

	@Reference
	protected SchemePersistence schemePersistence;

	@Reference
	protected SitePersistence sitePersistence;

	@Reference
	protected VMPersistence vmPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

}